firstproject/firstapp/urls.py
from django.urls import path
from firstapp import views

app_name = 'firstapp'

urlpatterns = [
    path('',views.BlogListView.as_view(), name='blog_list'),
    path('create',views.BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>',views.BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>',views.BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>',views.BlogDeleteView.as_view(), name='blog_delete'),
]

firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstapp/',include('firstapp.urls',namespace='firstapp')),
]

firstproject/firstapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100, null=True ,blank=True)
    author = models.CharField(max_length=100, null=True ,blank=True)
    message = models.TextField(null=True ,blank=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("firstapp.blog_list")
    

firstproject/firstapp/forms.py
from django import forms
from firstapp.models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields=['title','author','message']
        widgets={
            'title': forms.TextInput(attrs={'placeholder':'Enter the title of your post','class':'form-control'}),
            'author': forms.TextInput(attrs={'placeholder':'What is your name?','class':'form-control'}),
            'message': forms.Textarea(attrs={'placeholder':'What are you posting about','class':'form-control'}), 
        }

firstproject/firstapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView
from firstapp.models import Blog
from firstapp.forms import BlogForm
# Create your views here.
class BlogListView(ListView):
    model = Blog

    # Delivers/Look
    # looks for template firstapp/blog_list.html
    # Delivers list blog_list/object_list = Blog.object.all

# users in put data
class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    # fields=['title','author','message']

    # Delivers/looks for
    # looks for template firstapp/blog_form.html
    # Delivers list form = BlogForm()

class BlogDetailView(DetailView):
    model = Blog


    # Delivers/looks for
    # looks for template firstapp/blog_detail.html
    # Delivers list blog/object = Blog.object.get(pk=pk)

class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm
    # fields=['title','author','message']

    # Delivers/looks for
    # looks for template firstapp/blog_form.html
    # Delivers list form = BlogForm()

class BlogDeleteView(DeleteView):
    model = Blog
    
    # Delivers/looks for
    # looks for template firstapp/blog_confirm_delete.html
    # Delivers list blog/object = Blog.object.get(pk=pk)

    success_url = reverse_lazy('firstapp:blog_list')

firstproject/firstapp/templates/firstapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Demo Project">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
    crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" 
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" 
    crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'firstapp/css/style.css'%}">
</head>
<body>
    <img src="{% static 'firstapp/img/download.png' %}" alt="">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">modiSidom</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'firstapp:blog_list' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="'firstapp:blog_list'">List</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="'firstapp:blog_create'">Create</a>
                  </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Disabled</a>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>
    </header>
   <div class="container m-4">
 {% block content %}
     
 {% endblock %}
 </div>
</body>
<script> src="main.js" </script>
</html>

firstproject/firstapp/templates/firstapp/blog_confirm_delete.html
{% extends 'firstapp/base.html' %}

{% block content %}
    
<h1>Blog Form</h1>
    <form method="POST">
        {% csrf_token %}
        <p class="lead">Would you like to Delete {{blog}}</p>
        <input class="btn btn-danger" type="submit" value="Delete">
    </form>


{% endblock %}

firstproject/firstapp/templates/firstapp/blog_detail.html
{% extends 'firstapp/base.html' %}

{% block content %}
    
<h1>Blog Detail</h1>

    <div class="card">
        <div class="card-header bg-dark text-white">
            <a href="{% url 'firstapp:blog_detail' pk=blog.pk %}">{{blog.title}}</a>
        </div>
        <div class="card-body">
            {{blog.message}}
            {{blog.author}}
        </div>
    </div>

    <a class='btn btn-primary' href="{% url 'firstapp:blog_list' %}"> See All the Posts</a>
    <a class='btn btn-info' href="{% url 'firstapp:blog_update' pk=blog.pk %}"> Update</a>
    <a class='btn btn-danger' href="{% url 'firstapp:blog_delete' pk=blog.pk %}"> Delete</a>


{% endblock %}

firstproject/firstapp/templates/firstapp/blog_form.html
{% extends 'firstapp/base.html' %}

{% block content %}
    
<h1>Blog Form</h1>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
        <p>{{field}}</p>
        {% endfor %}
        <input class="btn btn-block btn-info" type="submit" value="Create">
    </form>


{% endblock %}

firstproject/firstapp/templates/firstapp/blog_list.html
{% extends 'firstapp/base.html' %}

{% block content %}
    
<h1>Blog List</h1>


{% if blog_list %}  
    <a href="{% url 'firstapp:blog_create' %}"> Create a post!</a>
    {% for blog in blog_list %}
    <div class="card">
        <div class="card-header bg-dark text-white">
            <a href="{% url 'firstapp:blog_detail' pk=blog.pk %}">{{blog.title}}</a>
        </div>
        <div class="card-body">
            {{blog.message}}
            {{blog.author}}
        </div>
    </div>
    {% endfor %}
{% else %}
    <a href="{% url 'firstapp:blog_create' %}">
        Create a post!</a>
{% endif %}

{% endblock %}